[workspace]
git_tag_enable = true
git_release_enable = true

[[package]]
name = "nearest"
changelog_path = "CHANGELOG.md"
git_tag_name = "v{{ version }}"
git_release_name = "v{{ version }}"

[[package]]
name = "nearest-derive"
changelog_update = false
git_tag_enable = false
git_release_enable = false

[[package]]
name = "xtask"
publish = false
changelog_update = false
git_tag_enable = false
git_release_enable = false
