edition = "2024"
style_edition = "2024"
max_width = 100
use_small_heuristics = "Max"
tab_spaces = 2
reorder_imports = true
reorder_modules = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
