name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-02-10
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --all
      - run: cargo run --example expr
      - run: cargo run --example json
      - run: cargo run --example ecs
      - run: cargo run --example fs
      - run: cargo run --example fsm

  test-no-std:
    name: Test (no_std)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-02-10
      - uses: Swatinem/rust-cache@v2
      - run: cargo build -p nearest --no-default-features

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-02-10
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --tests --all-features -- -D warnings
      - run: cargo clippy -p nearest --no-default-features -- -D warnings
      - run: cargo clippy -p nearest --no-default-features --features alloc -- -D warnings

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-02-10
          components: rustfmt
      - run: cargo fmt --all -- --check

  doc:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-02-10
      - uses: Swatinem/rust-cache@v2
      - run: cargo doc --no-deps --all
        env:
          RUSTDOCFLAGS: -D warnings

  miri:
    name: Miri
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-02-10
          components: miri, rust-src
      - uses: Swatinem/rust-cache@v2
      - run: cargo miri test -p nearest --lib --test integration
        env:
          MIRIFLAGS: -Zmiri-permissive-provenance

  deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rm rust-toolchain
      - uses: EmbarkStudios/cargo-deny-action@v2
